language: ruby

rvm:
  - 2.6.0
  - 2.7.0
  - 3.0.0
  - jruby-9.1.7.0
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem update bundler

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
